# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 315)
        self.pushButton_choose = QtWidgets.QPushButton(Form)
        self.pushButton_choose.setGeometry(QtCore.QRect(0, 10, 501, 51))
        self.pushButton_choose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 70, 291, 16))
        self.label.setObjectName("label")
        self.label_choosen_file = QtWidgets.QLabel(Form)
        self.label_choosen_file.setGeometry(QtCore.QRect(0, 90, 501, 16))
        self.label_choosen_file.setObjectName("label_choosen_file")
        self.pushButton_convert = QtWidgets.QPushButton(Form)
        self.pushButton_convert.setGeometry(QtCore.QRect(0, 130, 501, 51))
        self.pushButton_convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.label_file_2 = QtWidgets.QLabel(Form)
        self.label_file_2.setGeometry(QtCore.QRect(0, 190, 501, 16))
        self.label_file_2.setObjectName("label_file_2")
        self.label_converted_file = QtWidgets.QLabel(Form)
        self.label_converted_file.setGeometry(QtCore.QRect(0, 210, 501, 16))
        self.label_converted_file.setObjectName("label_converted_file")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 250, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_choose.setText(_translate("Form", "Choose the .ui File"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Choosen File:</span></p></body></html>"))
        self.label_choosen_file.setText(_translate("Form", "<html><head/><body><p>no file selected</p></body></html>"))
        self.pushButton_convert.setText(_translate("Form", "Convert File to Executable .py File and Save"))
        self.label_file_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Converted File:</span></p></body></html>"))
        self.label_converted_file.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
